[package]
name = "pub-code39"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
inquire = "0.6.2"
lazy_static = "1.4.0"
